### ISSUE TITLE
when I run the sync_operation.py in examples, an error occurred

### ISSUE THREAD

**Issue by acorn50** [christiansandberg/aioisotp#1]
DEBUG:can:can config: {'interface': 'virtual', 'channel': 'vcan0'}
DEBUG:asyncio:Using selector: SelectSelector
DEBUG:asyncio:Using selector: SelectSelector
Traceback (most recent call last):
  File "E:/async/uds_sync.py", line 15, in <module>
    client = network.create_sync_connection(0x123, 0x456)
  File "D:\python3.5\lib\site-packages\aioisotp\sync.py", line 42, in create_sync_connection
    _, protocol = fut.result(timeout=1)
  File "D:\python3.5\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "D:\python3.5\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\python3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\python3.5\lib\site-packages\aioisotp\network.py", line 120, in create_connection
    return self._make_userspace_transport(protocol_factory, rxid, txid)
  File "D:\python3.5\lib\site-packages\aioisotp\network.py", line 123, in _make_userspace_transport
    protocol = protocol_factory()
  File "D:\python3.5\lib\site-packages\aioisotp\sync.py", line 62, in __init__
    loop = asyncio.get_event_loop()
  File "D:\python3.5\lib\asyncio\events.py", line 632, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "D:\python3.5\lib\asyncio\events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.

**Comment by christiansandberg** [comment]
I think I have solved this. Please try the master when you can.

**Comment by acorn50** [comment]
yes,this problem have been solved
